spring.application.name=vento
server.port=8080


# Datasource properties

spring.datasource.url=jdbc:postgresql://localhost:5432/vento_db
spring.datasource.username=postgres
spring.datasource.password=1234


# The driver class name is usually auto-configured in modern Spring Boot apps
# spring.datasource.driver-class-name=org.postgresql.Driver

# JPA and Hibernate properties
#spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true


token.signing.key=190dcaa9c17f57db26a24d9520311fabe7a8730b6d918d6683e2c34247ade723
jwt.expiration=86400000


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username= klintzhan005@gmail.com
spring.mail.password= ahpg szdb bhel fhib
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true