CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TYPE user_role AS ENUM ('OWNER', 'MANAGER', 'WAREHOUSE_KEEPER');

CREATE TYPE transaction_type AS ENUM ('IN', 'OUT', 'TRANSFER', 'ADJUSTMENT');

CREATE TYPE token_type AS ENUM ('PASSWORD_RESET', 'EMAIL_VERIFICATION');

CREATE TYPE user_status AS ENUM (
    'ACTIVE',
    'INACTIVE',
    'BLOCKED',
    'DELETED',
    'PENDING'
);